# Generated by Django 3.0.8 on 2020-09-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200902_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks'),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Project'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.TaskGroup'),
        ),
    ]
